# Generated by Django 3.0.2 on 2020-05-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
