# Generated by Django 3.0.6 on 2020-06-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20200627_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='bill.Commande'),
            preserve_default=False,
        ),
    ]
